# Generated by Django 4.2.20 on 2025-04-19 10:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_toman', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_trx', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('trx_address', models.CharField(blank=True, max_length=34, null=True, unique=True)),
                ('encrypted_private_key', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdrawal', 'برداشت'), ('payment', 'پرداخت سبد خرید')], max_length=20)),
                ('currency', models.CharField(choices=[('toman', 'تومان'), ('trx', 'TRX')], max_length=10)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('authority', models.CharField(blank=True, max_length=36, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل\u200cشده'), ('failed', 'ناموفق')], default='pending', max_length=20)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
        ),
    ]
